kind: wasmer.io/App.v0
name: sentiero-draghi
package: .

services:
  - name: web
    run: python -m flask --app /src/app run --host=0.0.0.0 --port=8080 --no-reload
    ports:
      - port: 5000
        type: http
    env:
      - name: SECRET_KEY
        value: change-me-in-wasmer
      - name: FLASK_DEBUG
        value: "false"
owner: ddalbello01
env:
  PYTHONPATH: /site-packages
  PYTHONEXECUTABLE: /bin/python
app_id: da_RvJI4t0UXxx8
